name: todo-app-deployment
on: 
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - 'kubernetes/frontproxy/deployment.yaml'
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: todo-application
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      run: |
        docker build -t leopincle/todoapp:${{ github.sha }} . 
        docker push leopincle/todoapp:${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: leopincle/kubernetes-manifests
        path: kubernetes-manifests
    - name: Verify file structure
      run: |
          ls -R $GITHUB_WORKSPACE/todo-application
          ls -R $GITHUB_WORKSPACE/kubernetes-manifests
    - name: Updating deployment file with new image tag
      run: |
        sed -i 's|image: leopincle/todoapp:.*|image: leopincle/todoapp:${{ github.sha }}|g' $GITHUB_WORKSPACE/kubernetes-manifests/todo-app/deployment.yaml
        